# ACCOUNTS table:

SELECT * FROM accounts;

# What are the distinct sectors present in the table, and how many companies belong to each sector?
SELECT sector, COUNT(*) AS num_companies
FROM accounts
GROUP BY sector;

# Which company has the highest revenue, and what is its revenue?
SELECT account, revenue
FROM accounts
ORDER BY revenue DESC
LIMIT 1;

# How many companies were established each year?
SELECT year_established, COUNT(*) AS num_companies
FROM accounts
GROUP BY year_established
ORDER BY year_established;

# What is the average revenue and number of employees for each sector?
SELECT sector, round(AVG(revenue), 2)AS avg_revenue, round(AVG(employees), 2) AS avg_employees
FROM accounts
GROUP BY sector;

# How many subsidiaries does each parent company have?
SELECT subsidiary_of, COUNT(*) AS num_subsidiaries
FROM accounts
WHERE subsidiary_of IS NOT NULL
GROUP BY subsidiary_of;

# Which country has the highest number of companies, and how many companies are based there?
SELECT office_location, COUNT(*) AS num_companies
FROM accounts
GROUP BY office_location
ORDER BY num_companies DESC
LIMIT 1;

# What is the total revenue generated by companies established before the year 2000?
SELECT SUM(revenue) AS total_revenue
FROM accounts
WHERE year_established < 2000;

# What are the top 5 companies with the highest number of employees?
SELECT account, employees
FROM accounts
ORDER BY employees DESC
LIMIT 5;










